# Generated by Django 3.0.8 on 2021-08-24 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crusherdetail',
            name='user',
        ),
        migrations.RemoveField(
            model_name='minedetail',
            name='user',
        ),
    ]
