# Generated by Django 3.0.8 on 2021-08-31 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210824_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='is_crusher_inbound',
        ),
        migrations.RemoveField(
            model_name='company',
            name='is_crusher_outbound',
        ),
        migrations.RemoveField(
            model_name='company',
            name='is_master',
        ),
        migrations.RemoveField(
            model_name='company',
            name='is_mine_transaction',
        ),
        migrations.RemoveField(
            model_name='company',
            name='shourt_name',
        ),
        migrations.AddField(
            model_name='productmaster',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vehiclemaster',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
