# Generated by Django 3.0.8 on 2021-09-05 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210831_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_crusher_inbound',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='company',
            name='is_crusher_outbound',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='company',
            name='is_master',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='company',
            name='is_mine_transaction',
            field=models.BooleanField(default=True),
        ),
    ]
