# Generated by Django 3.0.8 on 2021-09-05 16:28

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210905_2129'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200, unique=True)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('customer_type', models.CharField(choices=[('individual', 'Individual'), ('properitor', 'Properitor'), ('partner', 'Partner'), ('llp', 'LLP'), ('pvt_ltd', 'PVT LTD'), ('ltd', 'LTD')], max_length=50, null=True)),
                ('pan_no', models.CharField(blank=True, max_length=50, null=True)),
                ('pan_file', models.FileField(blank=True, null=True, upload_to='file/', validators=[accounts.models.validate_file_size])),
                ('email', models.EmailField(blank=True, max_length=150, null=True)),
                ('gst_no', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('gst_file', models.FileField(blank=True, null=True, upload_to='file/', validators=[accounts.models.validate_file_size])),
                ('cin_no', models.CharField(blank=True, max_length=50, null=True)),
                ('cin_file', models.FileField(blank=True, null=True, upload_to='file/', validators=[accounts.models.validate_file_size])),
                ('credit_limit', models.CharField(blank=True, max_length=50, null=True)),
                ('project_status', models.CharField(blank=True, choices=[('on_hold', 'On Hold'), ('on_going', 'On Going'), ('completed', 'Completed')], max_length=20, null=True)),
                ('remark', models.TextField(blank=True, max_length=2000, null=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_added_by', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_company', to='accounts.NewCustomer')),
            ],
        ),
    ]
