# Generated by Django 3.0.8 on 2021-09-07 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_newcustomer'),
    ]

    operations = [
        migrations.AddField(
            model_name='crusherdetail',
            name='customer_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_crusher_detail', to='accounts.NewCustomer'),
        ),
        migrations.AddField(
            model_name='minedetail',
            name='customer_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_mine_detail', to='accounts.NewCustomer'),
        ),
        migrations.AddField(
            model_name='owner',
            name='customer_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_owner', to='accounts.NewCustomer'),
        ),
        migrations.AddField(
            model_name='productmaster',
            name='customer_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_products', to='accounts.NewCustomer'),
        ),
        migrations.AddField(
            model_name='vehiclemaster',
            name='customer_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_vehicle', to='accounts.NewCustomer'),
        ),
    ]
