# Generated by Django 3.0.8 on 2021-09-07 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20210907_0720'),
    ]

    operations = [
        migrations.AddField(
            model_name='newcustomer',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
