# Generated by Django 3.0.8 on 2021-09-07 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_newcustomer_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newcustomer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
