# Generated by Django 3.0.8 on 2021-09-08 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20210907_0803'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmaster',
            name='gst_percent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
