# Generated by Django 3.0.8 on 2021-09-09 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20210909_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='myuser',
            field=models.BooleanField(default=False),
        ),
    ]
