# Generated by Django 3.0.8 on 2021-09-10 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_userprofile_myuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='sort_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
