# Generated by Django 3.0.8 on 2021-09-10 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_company_sort_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='newcustomer',
            name='customer_category',
            field=models.CharField(choices=[('client', 'Client'), ('vendor', 'Vendor'), ('transporter', 'Transporter'), ('individual', 'Individual'), ('properitor', 'Properitor'), ('partner', 'Partner'), ('llp', 'LLP'), ('pvt_ltd', 'PVT LTD'), ('ltd', 'LTD')], max_length=50, null=True),
        ),
    ]
