# Generated by Django 3.0.8 on 2021-09-13 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20210910_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_type',
            field=models.CharField(choices=[('client', 'Client'), ('vendor', 'Vendor'), ('mine', 'Mine'), ('crusher', 'Crusher'), ('minecrusher', 'Mine&Crusher'), ('contractor', 'Contractor'), ('transporter', 'Transporter'), ('individual', 'Individual'), ('properitor', 'Properitor'), ('partner', 'Partner'), ('llp', 'LLP'), ('pvt_ltd', 'PVT LTD'), ('ltd', 'LTD')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='customer_category',
            field=models.CharField(choices=[('client', 'Client'), ('vendor', 'Vendor'), ('mine', 'Mine'), ('crusher', 'Crusher'), ('minecrusher', 'Mine&Crusher'), ('contractor', 'Contractor'), ('transporter', 'Transporter'), ('individual', 'Individual'), ('properitor', 'Properitor'), ('partner', 'Partner'), ('llp', 'LLP'), ('pvt_ltd', 'PVT LTD'), ('ltd', 'LTD')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='customer_type',
            field=models.CharField(choices=[('client', 'Client'), ('vendor', 'Vendor'), ('mine', 'Mine'), ('crusher', 'Crusher'), ('minecrusher', 'Mine&Crusher'), ('contractor', 'Contractor'), ('transporter', 'Transporter'), ('individual', 'Individual'), ('properitor', 'Properitor'), ('partner', 'Partner'), ('llp', 'LLP'), ('pvt_ltd', 'PVT LTD'), ('ltd', 'LTD')], max_length=50, null=True),
        ),
    ]
