# Generated by Django 3.0.8 on 2021-09-14 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20210913_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='crusherdetail',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='minedetail',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='id',
            field=models.PositiveSmallIntegerField(choices=[(15, 'master'), (16, 'mine_transaction'), (17, 'crusher_inbound'), (18, 'crusher_outbound'), (4, 'superuser'), (3, 'admin'), (2, 'hr'), (1, 'client'), (5, 'company1'), (6, 'company2'), (7, 'company3'), (8, 'customer'), (9, 'product'), (10, 'vehicle'), (11, 'mine'), (12, 'crusher'), (13, 'owner'), (14, 'newuser')], default=15, primary_key=True, serialize=False),
        ),
    ]
