# Generated by Django 3.0.8 on 2021-09-14 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20210914_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='crusherdetail',
            name='na',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vehiclemaster',
            name='na',
            field=models.BooleanField(default=True),
        ),
    ]
