# Generated by Django 3.0.8 on 2021-09-14 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20210914_1048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiclemaster',
            name='na',
        ),
        migrations.AddField(
            model_name='minedetail',
            name='na',
            field=models.BooleanField(default=True),
        ),
    ]
