# Generated by Django 3.0.8 on 2021-09-14 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20210914_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclemaster',
            name='driver_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vehiclemaster',
            name='mobile',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
