# Generated by Django 3.0.8 on 2021-09-16 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_auto_20210914_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='sale_category',
            field=models.CharField(choices=[('mine', 'Mine'), ('crusher', 'Crusher'), ('distributer', 'Distributer,1'), ('nhai', 'NHAI,1'), ('precast', 'Precast,1'), ('real_estate', 'Real Estate,1'), ('rmc', 'RMC,1'), ('supplier', 'Supplier,1'), ('stp', 'STP,1'), ('water_treatment_htp', 'Water Treatment & HTP,1'), ('infra_projects', 'Infra Projects,1'), ('retail', 'Retail,1'), ('metro', 'Metro,1'), ('pwd', 'PWD,1')], max_length=50, null=True),
        ),
    ]
