# Generated by Django 3.0.8 on 2021-09-17 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_myuser_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclemaster',
            name='insurance_validity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclemaster',
            name='pollution_validity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclemaster',
            name='purchase_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
