# Generated by Django 3.0.8 on 2021-09-21 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_auto_20210921_2010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='minedetail',
            name='customer_name',
        ),
        migrations.AddField(
            model_name='minedetail',
            name='customer_name',
            field=models.ManyToManyField(blank=True, to='accounts.NewCustomer'),
        ),
    ]
