# Generated by Django 3.0.8 on 2021-09-22 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_auto_20210921_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='crusher',
            field=models.ManyToManyField(blank=True, related_name='multiple_crushers', to='accounts.CrusherDetail'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mines',
            field=models.ManyToManyField(blank=True, related_name='multiple_mines', to='accounts.MineDetail'),
        ),
    ]
