# Generated by Django 3.0.8 on 2021-09-23 06:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_auto_20210922_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_myuser', to=settings.AUTH_USER_MODEL),
        ),
    ]
