# Generated by Django 3.0.8 on 2021-09-23 11:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_auto_20210923_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_submaster',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='id',
            field=models.PositiveSmallIntegerField(choices=[(15, 'master'), (19, 'submaster'), (16, 'mine_transaction'), (17, 'crusher_inbound'), (18, 'crusher_outbound'), (4, 'superuser'), (3, 'admin'), (2, 'hr'), (1, 'client'), (5, 'company1'), (6, 'company2'), (7, 'company3'), (8, 'customer'), (9, 'product'), (10, 'vehicle'), (11, 'mine'), (12, 'crusher'), (13, 'owner'), (14, 'newuser')], default=15, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='MineralType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_mineral', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
