# Generated by Django 3.0.8 on 2021-10-01 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_newcustomer_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newcustomer',
            name='customer_mine',
            field=models.ManyToManyField(blank=True, to='accounts.CustomerMine'),
        ),
    ]
