# Generated by Django 3.0.8 on 2021-10-02 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_auto_20211001_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crusherdetail',
            name='coordinate_a',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='crusherdetail',
            name='coordinate_b',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='crusherdetail',
            name='coordinate_c',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='crusherdetail',
            name='coordinate_d',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='crusherdetail',
            name='owner',
            field=models.ManyToManyField(blank=True, to='accounts.Owner'),
        ),
        migrations.AlterField(
            model_name='minedetail',
            name='coordinate_a',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='minedetail',
            name='coordinate_b',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='minedetail',
            name='coordinate_c',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='minedetail',
            name='coordinate_d',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='minedetail',
            name='owner',
            field=models.ManyToManyField(blank=True, to='accounts.Owner'),
        ),
    ]
