# Generated by Django 3.0.8 on 2021-10-04 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_auto_20211002_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclemaster',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('tractor', 'Tractor'), ('truck 6 tyres', 'Truck 6 Tyres'), ('truck 10 tyres', 'Truck 10 Tyres'), ('truck 20 tyres', 'Truck 20 Tyres'), ('trailer', 'Trailer')], max_length=200, null=True),
        ),
    ]
