# Generated by Django 3.0.8 on 2021-10-27 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_company_is_dynamic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiclemaster',
            name='driver_name',
        ),
        migrations.CreateModel(
            name='DriverMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver_name', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile', models.CharField(blank=True, max_length=16, null=True)),
                ('age', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, max_length=2000, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('company_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_driver', to='accounts.Company')),
                ('customer_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_driver', to='accounts.NewCustomer')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_driver_master', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ManyToManyField(blank=True, to='accounts.VehicleMaster')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='vehiclemaster',
            name='driver_name',
            field=models.ManyToManyField(blank=True, to='accounts.DriverMaster'),
        ),
    ]
