# Generated by Django 3.0.8 on 2021-11-10 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_auto_20211027_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='id',
            field=models.PositiveSmallIntegerField(choices=[(15, 'master'), (19, 'submaster'), (16, 'mine_transaction'), (17, 'crusher_inbound'), (18, 'crusher_outbound'), (4, 'superuser'), (3, 'admin'), (2, 'hr'), (1, 'client'), (5, 'company1'), (6, 'company2'), (7, 'company3'), (8, 'customer'), (9, 'product'), (10, 'vehicle'), (11, 'mine'), (12, 'crusher'), (13, 'owner'), (14, 'newuser'), (20, 'machine'), (21, 'driver'), (22, 'expense'), (23, 'meterial_inward'), (24, 'indatetime'), (25, 'wb_operator')], default=15, primary_key=True, serialize=False),
        ),
    ]
