# Generated by Django 3.0.8 on 2021-12-11 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0047_auto_20211206_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_autoinvoice_no',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='company',
            name='prefix_invoice_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='purchase_prefix',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='purchases_transaction_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='sale_prefix',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='sale_transaction_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
