# Generated by Django 3.0.8 on 2021-12-13 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0047_auto_20211206_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_type',
            field=models.CharField(choices=[('kaata', 'Kaata'), ('client', 'Client'), ('vendor', 'Vendor'), ('mine', 'Mine'), ('crusher', 'Crusher'), ('minecrusher', 'Mine&Crusher'), ('contractor', 'Contractor'), ('transporter', 'Transporter'), ('individual', 'Individual'), ('properitor', 'Properitorship Firm'), ('partner', 'Partner Firm'), ('llp', 'Limited Liability Partnership(LLP)'), ('pvt_ltd', 'Private Limited Company'), ('ltd', 'Public Limited Company'), ('isd', 'Indian Subsidiary'), ('nidhi', 'Nidhi Company'), ('ngo', 'Sec 25/Sec8 Company(NGO)'), ('huf', 'Hindu Undivided Family(HUF)')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='customer_category',
            field=models.CharField(choices=[('kaata', 'Kaata'), ('client', 'Client'), ('vendor', 'Vendor'), ('mine', 'Mine'), ('crusher', 'Crusher'), ('minecrusher', 'Mine&Crusher'), ('contractor', 'Contractor'), ('transporter', 'Transporter'), ('individual', 'Individual'), ('properitor', 'Properitorship Firm'), ('partner', 'Partner Firm'), ('llp', 'Limited Liability Partnership(LLP)'), ('pvt_ltd', 'Private Limited Company'), ('ltd', 'Public Limited Company'), ('isd', 'Indian Subsidiary'), ('nidhi', 'Nidhi Company'), ('ngo', 'Sec 25/Sec8 Company(NGO)'), ('huf', 'Hindu Undivided Family(HUF)')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='customer_type',
            field=models.CharField(choices=[('kaata', 'Kaata'), ('client', 'Client'), ('vendor', 'Vendor'), ('mine', 'Mine'), ('crusher', 'Crusher'), ('minecrusher', 'Mine&Crusher'), ('contractor', 'Contractor'), ('transporter', 'Transporter'), ('individual', 'Individual'), ('properitor', 'Properitorship Firm'), ('partner', 'Partner Firm'), ('llp', 'Limited Liability Partnership(LLP)'), ('pvt_ltd', 'Private Limited Company'), ('ltd', 'Public Limited Company'), ('isd', 'Indian Subsidiary'), ('nidhi', 'Nidhi Company'), ('ngo', 'Sec 25/Sec8 Company(NGO)'), ('huf', 'Hindu Undivided Family(HUF)')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='PowerFactor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kvah', models.CharField(blank=True, max_length=20, null=True)),
                ('kwh', models.CharField(blank=True, max_length=20, null=True)),
                ('netkvah', models.CharField(blank=True, max_length=20, null=True)),
                ('netkwh', models.CharField(blank=True, max_length=20, null=True)),
                ('lockkvah', models.CharField(blank=True, max_length=20, null=True)),
                ('lockkwh', models.CharField(blank=True, max_length=20, null=True)),
                ('power', models.CharField(blank=True, max_length=20, null=True)),
                ('Added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='power_added_by', to=settings.AUTH_USER_MODEL)),
                ('company_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='power_company', to='accounts.Company')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
