# Generated by Django 3.0.8 on 2022-01-04 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0048_auto_20211213_1535'),
        ('accounts', '0048_auto_20211211_2318'),
    ]

    operations = [
    ]
