# Generated by Django 3.0.8 on 2022-04-07 05:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mobi58.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mobi58', '0002_auto_20220407_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile', models.CharField(blank=True, max_length=16, null=True)),
                ('age', models.CharField(blank=True, max_length=50, null=True)),
                ('license_no', models.CharField(blank=True, max_length=50, null=True)),
                ('license_file', models.FileField(blank=True, null=True, upload_to='file/dl/', validators=[mobi58.models.validate_file_size])),
                ('aadhar_no', models.CharField(blank=True, max_length=50, null=True)),
                ('aadhar_file', models.FileField(blank=True, null=True, upload_to='file/aadhar/', validators=[mobi58.models.validate_file_size])),
                ('address', models.TextField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, max_length=2000, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('transporter_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mobi58.Transporter')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='mobi58.vehicleRegister')),
            ],
        ),
    ]
