# Generated by Django 3.0.8 on 2022-05-16 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobi58', '0005_auto_20220408_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='age',
        ),
        migrations.AddField(
            model_name='driver',
            name='DOB',
            field=models.DateField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleregister',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('two_wheeler', 'Two-Wheeler'), ('three_wheeler', 'Three-Wheeler'), ('four_wheeler', 'Four-Wheeler')], max_length=100, null=True),
        ),
    ]
