# Generated by Django 3.0.8 on 2022-06-29 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobi58', '0008_auto_20220628_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtrip',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='addtrip',
            name='Fixed_amount_btw_s_d',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='addtrip',
            name='approx_distance',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
