# Generated by Django 3.0.8 on 2022-06-30 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobi58', '0009_auto_20220629_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleregister',
            name='registeration_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='vehicleregister',
            name='registered_upto',
            field=models.DateField(null=True),
        ),
    ]
