# Generated by Django 3.0.8 on 2022-06-30 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobi58', '0010_auto_20220630_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleregister',
            name='chasis_no',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='vehicleregister',
            name='engine_no',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
