# Generated by Django 3.0.8 on 2022-06-30 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobi58', '0011_auto_20220630_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleregister',
            name='registeration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleregister',
            name='registeration_no',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='vehicleregister',
            name='registered_upto',
            field=models.DateField(blank=True, null=True),
        ),
    ]
