# Generated by Django 3.0.8 on 2022-06-30 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobi58', '0012_auto_20220630_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleregister',
            name='trransporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mobi58.Transporter'),
        ),
    ]
