# Generated by Django 3.0.8 on 2022-06-30 09:46

from django.db import migrations, models
import mobi58.models


class Migration(migrations.Migration):

    dependencies = [
        ('mobi58', '0014_auto_20220630_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtrip',
            name='destination',
            field=models.CharField(blank=True, choices=[('JAIPUR', 'JAIPUR'), ('AHEMADABAD', 'AHMEDABAD'), ('DELHI', 'DELHI')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='addtrip',
            name='source',
            field=models.CharField(blank=True, choices=[('DILPURA', 'DILPURA'), ('BANAR', 'BANAR'), ('NAURANGPUR', 'NAURANGPUR')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleregister',
            name='fuel_type',
            field=models.CharField(blank=True, choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('CNG', 'CNG'), ('Electric', 'Electric')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleregister',
            name='insurance_file',
            field=models.FileField(blank=True, null=True, upload_to='file/vehicle/', validators=[mobi58.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='vehicleregister',
            name='pollution_file',
            field=models.FileField(blank=True, null=True, upload_to='file/vehicle/', validators=[mobi58.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='vehicleregister',
            name='rc_file',
            field=models.FileField(blank=True, null=True, upload_to='file/vehicle/', validators=[mobi58.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='vehicleregister',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('Two-Wheeler', 'Two-Wheeler'), ('Three-Wheeler', 'Three-Wheeler'), ('Four-Wheeler', 'Four-Wheeler')], max_length=100, null=True),
        ),
    ]
