# Generated by Django 3.0.8 on 2022-07-05 05:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mobi58', '0015_auto_20220630_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='productManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_location', models.CharField(blank=True, choices=[('DILPURA', 'DILPURA'), ('BANAR', 'BANAR'), ('NAURANGPUR', 'NAURANGPUR')], max_length=100, null=True)),
                ('module', models.CharField(blank=True, choices=[('LOGI58', 'LOGI58'), ('MOBI58', 'MOBI58'), ('MACHINE58', 'MACHINE58')], max_length=100, null=True)),
                ('fuel', models.CharField(blank=True, choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('CNG', 'CNG'), ('Electric', 'Electric')], max_length=100, null=True)),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('rate', models.PositiveIntegerField(blank=True, null=True)),
                ('amount', models.PositiveIntegerField(blank=True, null=True)),
                ('Date', models.DateField(auto_now_add=True)),
                ('comments', models.CharField(blank=True, max_length=900, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('reg_no', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='mobi58.vehicleRegister')),
                ('user_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
