# Generated by Django 3.0.8 on 2022-07-05 06:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mobi58', '0016_productmanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmanager',
            name='assign_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='productmanager',
            name='user_type',
            field=models.CharField(blank=True, choices=[('USERS', 'USERS'), ('CONTRACTORS', 'CONTRACTORS')], max_length=100, null=True),
        ),
    ]
