# Generated by Django 3.0.8 on 2022-02-02 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='raiseticket',
            name='status',
            field=models.CharField(choices=[('PD', 'Pending'), ('AP', 'Approved'), ('AC', 'Active'), ('CL', 'Closed')], default='PD', max_length=30),
        ),
    ]
