# Generated by Django 3.0.8 on 2022-02-03 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Ticket', '0006_raiseticket_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raiseticket',
            name='assign_to',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
