# Generated by Django 3.0.8 on 2022-02-07 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0011_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assign',
        ),
        migrations.RemoveField(
            model_name='task',
            name='project',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='name',
        ),
        migrations.RemoveField(
            model_name='raiseticket',
            name='fullname',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
