# Generated by Django 3.0.8 on 2022-02-07 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0012_auto_20220207_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='raiseticket',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
