# Generated by Django 3.0.8 on 2022-02-07 17:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Ticket', '0013_raiseticket_is_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raiseticket',
            name='accepted',
        ),
        migrations.RemoveField(
            model_name='raiseticket',
            name='admin_response',
        ),
        migrations.RemoveField(
            model_name='raiseticket',
            name='email',
        ),
        migrations.RemoveField(
            model_name='raiseticket',
            name='is_aprove',
        ),
        migrations.RemoveField(
            model_name='raiseticket',
            name='status',
        ),
        migrations.AddField(
            model_name='raiseticket',
            name='time_period',
            field=models.CharField(blank=True, choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Manual', 'Manual')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='raiseticket',
            name='assign_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
