# Generated by Django 3.0.8 on 2022-02-13 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0016_auto_20220208_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='Notif',
        ),
    ]
