# Generated by Django 3.0.8 on 2022-02-13 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0017_auto_20220213_2133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='name',
        ),
    ]
