# Generated by Django 3.0.8 on 2022-03-02 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0020_auto_20220302_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='raiseticket',
            name='assigned_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
