# Generated by Django 3.0.8 on 2022-03-09 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0022_auto_20220309_1126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='raiseticket',
            old_name='imgs',
            new_name='img',
        ),
    ]
