# Generated by Django 3.0.8 on 2022-03-09 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0025_auto_20220309_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raiseticket',
            name='priority',
            field=models.CharField(choices=[('High', 'High'), ('Low', 'Low'), ('Medium', 'Medium')], default='Medium', max_length=50),
        ),
    ]
