# Generated by Django 3.0.8 on 2022-03-10 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0027_auto_20220309_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='raiseticket',
            name='status',
            field=models.CharField(choices=[('PD', 'Pending'), ('AP', 'Approved'), ('AC', 'Active'), ('CL', 'Closed'), ('CP', 'Complete'), ('WIP', 'Work in Progress')], default='WIP', max_length=30),
        ),
    ]
