# Generated by Django 3.0.8 on 2022-03-11 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0029_auto_20220310_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='raiseticket',
            name='Type',
            field=models.CharField(blank=True, choices=[('Query', 'Query'), ('Suggestion', 'Suggestion'), ('Complaint', 'Complaint')], max_length=50, null=True),
        ),
    ]
