# Generated by Django 3.0.8 on 2022-03-13 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0032_auto_20220313_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Ticket.RaiseTicket'),
        ),
    ]
