# Generated by Django 3.0.8 on 2022-03-15 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0034_auto_20220314_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raiseticket',
            name='assigned_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
